export const MOCK_PRODUCTS = [
  {
    id: 'mock-1',
    nameAr: 'عصير برتقال طازج',
    nameEn: 'Fresh Orange Juice',
    descriptionAr: 'برتقال طبيعي 100% بدون سكر مضاف.',
    descriptionEn: '100% natural orange juice with no added sugar.',
    price: '45.00',
    type: 'fresh',
    category: 'Traditional',
    images: ['https://images.unsplash.com/photo-1621506289937-48e46279d57c?auto=format&fit=crop&q=80&w=400'],
    visible: true,
  },
  {
    id: 'mock-2',
    nameAr: 'عصير مانجو استوائي',
    nameEn: 'Tropical Mango Juice',
    descriptionAr: 'مانجو فاخرة مبردة.',
    descriptionEn: 'Premium chilled mango.',
    price: '60.00',
    type: 'fresh',
    category: 'Blended',
    images: ['https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&q=80&w=400'],
    visible: true,
  },
  {
    id: 'mock-3',
    nameAr: 'باقة لتر - برتقال',
    nameEn: '1L Bottle - Orange',
    descriptionAr: 'زجاجة لتر للتوصيل أو الطلبات الكبيرة.',
    descriptionEn: '1L bottle for delivery or bulk orders.',
    price: '120.00',
    type: 'ready',
    category: 'Bulk',
    images: ['https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=400'],
    visible: true,
  },
  {
    id: 'mock-4',
    nameAr: 'عصير رمان ملكي',
    nameEn: 'Royal Pomegranate',
    descriptionAr: 'عصرة رمان خام مركزة.',
    descriptionEn: 'Raw concentrated pomegranate press.',
    price: '75.00',
    type: 'fresh',
    category: 'Seasonal',
    images: ['https://images.unsplash.com/photo-1618897996318-5a901fa6ca32?auto=format&fit=crop&q=80&w=400'],
    visible: true,
  }
];
